### ISSUE TITLE
How to install and run SvAnna?

### ISSUE THREAD

**Issue by aojielian** [TheJacksonLaboratory/SvAnna#215]
Hi,
Would you please provide a tutorial that how to install and run SvAnna?

Thanks

**Comment by ielis** [comment]
Hi, did you try the [docs](https://svanna.readthedocs.io/en/master)?

**Comment by aojielian** [comment]
> Hi, did you try the [docs](https://svanna.readthedocs.io/en/master)?

Cool, i didn't see that. Thanks
