### ISSUE TITLE
EMPTY results?

### ISSUE THREAD

**Issue by aojielian** [TheJacksonLaboratory/SvAnna#216]
Hi,
I run SvAnna with my VCF, but nothing output, it says:
Total number of genes affected by structural variants: 210
Total number of enhancers affected by structural variants: 0
We were unable to parse 0 entries.

Is that normal? my command line is:
java -jar svanna-cli-1.0.0/svanna-cli-1.0.0.jar prioritize -d svanna-data --vcf EOEE_fam03.pbsv.denovo.vcf  --phenotype-term HP:0004322 --phenotype-term HP:0001518  --out-dir results --prefix eoee3

and here is my vcf(generated by pbsv):
https://drive.google.com/file/d/1xfiSOCfbxQWg7Ko43Q9GqSTx7sbv0XCg/view?usp=sharing

Would you please tell me if it is the reason for vcf？
Thanks

**Comment by aojielian** [comment]
15:34:12.969 [main] INFO  o.m.svanna.cli.cmd.PrioritizeCommand - Reading variants from `EOEE_fam03.pbsv.denovo.vcf`
15:34:13.054 [main] WARN  o.m.svanna.io.parse.VcfVariantParser - Parsing symbolic variants with >1 genotype calls is not supported: chr1-202204235:(pbsv.SPLIT.DUP.3953)
15:34:13.060 [main] WARN  o.m.svanna.io.parse.VcfVariantParser - Parsing symbolic variants with >1 genotype calls is not supported: chr10-39568651:(pbsv.INS.DUP.6457)
15:34:13.061 [main] WARN  o.m.svanna.io.parse.VcfVariantParser - Parsing symbolic variants with >1 genotype calls is not supported: chr10-131041972:(pbsv.SPLIT.DUP.8388)

**Comment by ielis** [comment]
Hi @aojielian Can you please verify that you get correct output when running SvAnna on the [example.vcf](https://github.com/TheJacksonLaboratory/SvAnna/blob/master/svanna-cli/src/examples/example.vcf)? If the output is OK, then there *a)* something wrong with your input or *b)* there is a bug in the code. 

It's hard for me to know which one is the case based on the data you provided. I can't access your VCF, Google is asking for my credentials. Perhaps you can share the VCF lines of the variants that lead to warnings? (`pbsv.SPLIT.DUP:3953` etc). On top of that, SvAnna creates a log file in the folder that contains more information than what you posted above. Perhaps you can share the file? Or find another way how to share the VCF file?

**Comment by aojielian** [comment]
Yes, running SvAnna  on example.vcf is work for me, which generate the correct results. and i changed permission of my vcf, can you try that again?  
Thank you so much

**Comment by ielis** [comment]
Hi @aojielian , after seeing your VCF, I think the issue is that SvAnna does not support multi-sample VCFs at the moment.

So I ran the following to prepare single-sample VCF:
```shell
bcftools view --samples EOEE_fam03.p1 --exclude-uncalled EOEE_fam03.pbsv.denovo.vcf | bgzip -c > EOEE_fam03.EOEE_fam03.p1.pbsv.denovo.vcf.gz
```

and I ran SvAnna after that

```shell
java -jar svanna-cli.jar prioritize -d /path/to/my/2204_hg38  --phenotype-term HP:0004322 --phenotype-term HP:0001518 --vcf EOEE_fam03.EOEE_fam03.p1.pbsv.denovo.vcf.gz --prefix eoee3
```

to get:

```
08:50:25.797 [main] INFO  o.m.svanna.cli.cmd.SvAnnaCommand - Spooling up SvAnna v1.0.0 using resources in /path/to/my/2204_hg38
08:50:34.119 [main] INFO  o.m.svanna.cli.cmd.PrioritizeCommand - Reading variants from `EOEE_fam03.EOEE_fam03.p1.pbsv.denovo.vcf.gz`
08:50:34.230 [main] WARN  o.m.svanna.io.parse.VcfVariantParser - Invalid VCF record: `Line 130: there aren't enough columns for line chr4	190180280	pbsv.BND.chr4:190180280-chr14_GL000225v1_random:56661	A	A[chr14_GL000225v1_random:56661[	.	PASS	SVTYPE=BND;CIPOS=-4,4;MATEID=pbsv.BND.chr14_GL000225v1_random:56661-chr4:190180280;TRANSMITTED (we expected 9 tokens, and saw 8 )`: `chr4	190180280	pbsv.BND.chr4:190180280-chr14_GL000225v1_random:56661	A	A[chr14_GL000225v1_random:56661[	.	PASS	SVTYPE=BND;CIPOS=-4,4;MATEID=pbsv.BND.chr14_GL000225v1_random:56661-chr4:190180280;TRANSMITTED`
08:50:34.230 [main] INFO  o.m.svanna.cli.cmd.PrioritizeCommand - Read 130 variants
08:50:34.230 [main] INFO  o.m.svanna.cli.cmd.PrioritizeCommand - Filtering out the variants with reciprocal overlap >80.0% occurring in more than 1.0% probands
08:50:34.230 [main] INFO  o.m.svanna.cli.cmd.PrioritizeCommand - Filtering out the variants where ALT allele is supported by less than 3 reads
08:50:44.526 [main] INFO  o.m.svanna.cli.cmd.PrioritizeCommand - Prioritizing 130 variants on 2 threads
08:50:44.731 [main] INFO  o.m.svanna.cli.cmd.PrioritizeCommand - Prioritization finished in 0m 0s (203 ms) processing on average 640.39 items/s
08:50:44.731 [main] INFO  o.m.svanna.cli.cmd.PrioritizeCommand - Writing out the results
08:50:44.749 [main] INFO  o.m.s.c.writer.html.HtmlResultWriter - Writing HTML results to eoee3.html
08:50:48.910 [main] INFO  o.m.svanna.cli.cmd.PrioritizeCommand - We're done, bye!
```

The report looked OK, but there was no variant with a decent contribution from the 2 phenotype terms. So, I think the issue was the input - multi-sample VCF file.

**Comment by aojielian** [comment]
Thanks, it will generate the results. One more question would like to ask you that is HPO term will affect the results? For example, the EOEE (early-onset epileptic encephalopathy), in HPO has lots of phenotypes, in above case, i only use two of them,HP:0004322,Short stature and HP:0001518,Small for gestational age.
If i use all of these phenotypes, will the results be different?

**Comment by ielis** [comment]
The HPO selection will definitely affect the results, see [SvAnna paper](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-022-01046-6), in particular Figure 1B. The phenotype terms you provided do not really point to EOEE. Instead, you should provide a few terms that are more specific to EOEE.

**Comment by aojielian** [comment]
Got it, Thank you so much.

**Comment by aojielian** [comment]
I try that with another three HPO of EOEE. HP:0001298(Encephalopathy)、HP:0001250(Seizure)、HP:0001249(Intellectual disability), but the highest Priority score is like 3.00, is that decent results? and all results were used from pbsv denovo vcfs, should i try another VCFs? like pbsv.inherited vcf to get more decent results?

**Comment by ielis** [comment]
The terms sound better for EOEE. Based on the score being `3.00` it is likely that the phenotype weighting did not play a role. 

The PSV score of `3` is likely caused by a variant affecting 3 genes. However, there was probably no good match between a disease *D* associated with the gene(s) and the phenotype terms *Q* leading to phenotypic similarity (`\phi(Q,D)`, 2nd operand in equation 5 in SvAnna paper) value of `1`. Because of that, phenotypic similarity does not change the sequence deleteriousness score (`\delta(g)`, first operand) for any gene.

In general, you'll get a score `n` for a variant overlapping *n* genes if there is no good phenotype match. However, a good phenotype match leads to higher values and makes it easier to find the deleterious variants. See e.g. [deletion of multiple genes](https://svanna.readthedocs.io/en/master/examples.html#deletion-of-multiple-genes).

**Comment by aojielian** [comment]
Hi Daniel, 
I recently performed Oxford Nanopore sequencing on a patient with early-onset epileptic encephalopathy. And i used SvAnna to prioritizes SV variants.
The results show that there is a INV(chr12)(25803195; 125316602) (99.51 Mb)   Priority: 325.76
Is that a decent result? i mean is this INV too big to locate the disease-causing gene？This INV affected lot of genes. How can i narrowing the  results? add more HPO terms?
for this results, i got three HPO terms:
HP:0001298   HP:0001250  HP:0001249 

![截屏2022-07-14 14 03 12](https://user-images.githubusercontent.com/34530228/179434642-307ef856-1d39-4f4f-8cb1-a1eb9ad88a28.png)

**Comment by pnrobinson** [comment]
Hi there, my advice would be to look if the original data supports this call. The inversion encompasses about 75% of chromosome 12 and my initial suspicion would be that it is an artifact. It looks like there are 6 reads to support this -- check if the breakpoints are consistent etc.  If you believe there genuinely is an inversion of this size, then check whether one of the breakpoints disrupts a gene that might be involved in encephalopathy.
