### ISSUE TITLE
Using SVAnna in a trio VCF and withtou HPO terms

### ISSUE THREAD

**Issue by prasundutta87** [TheJacksonLaboratory/SvAnna#218]
Hi,

I have trio VCF which was generated using sniffles2 multisample SV calling program for rare disease research. Can that be successfully used to perform SVAnna annotation? All the examples seem to be focused towards only probands. Also, it seems that giving HPO IDs is a mandatory input. I understand the reason behind it, but is there a way to use SVAnna without giving in the HPO terms?

Regards,
Prasun

**Comment by ielis** [comment]
Hi @prasundutta87 , 
unfortunately, neither multi-sample analysis nor analysis without HPO terms is available at the moment.
