### ISSUE TITLE
SVanna weird error gencode.v38.genes.json.gz

### ISSUE THREAD

**Issue by Nelhachem** [TheJacksonLaboratory/SvAnna#234]
Hello,

Thank you for providing the SvAnna tool.
We have a vcf file created with Sniffles (long-read sequencing) and trying to run SvAnna based on the detailed documentation.
However, we still have this issue when running the script : ERROR o.m.svanna.cli.cmd.PrioritizeCommand - Error: Error reading genes from `gencode.v38.genes.json.gz`
Any hint ? this might be a naive error
gencode.v38.genes.json.gz is in the same folder as svanna_db.mv.db and the jar file

Thanks in advance

Nehme

**Comment by ielis** [comment]
Hi @Nelhachem 
on the first glance this looks like installation/setup error but I need more information for troubleshooting.

Can you please share the following:
- command which you ran to execute SvAnna
- contents of the SvAnna data directory - the directory passed via `-d | --data-directory` CLI option

Thank you,
Daniel

**Comment by Nelhachem** [comment]
Hi Daniel,

Thanks a bunch for your prompt reply.
I have managed to run the program by modifying some permissions on our server. I've downloaded the latest hg38.zip file.
I'll let you know if other issues emerge.

Kind regards,

Nem
