### ISSUE TITLE
PSV threshold

### ISSUE THREAD

**Issue by Tahyne** [TheJacksonLaboratory/SvAnna#241]
Nice tool!
Is there any threshold (or range) applicable to select the most pathogenic SVs?  
PSV results went from 1.38 to 218.49.

Also, do you recommend that even with a low psv in one sample it could be pathogenic if I found the same SV recurrently in at least 30% of the samples? Or any recurrence?

And, how do I could select the correct (best) transcript? Should be the canonical (1st)?

**Comment by ielis** [comment]
Hi @Tahyne 

> Is there any threshold (or range) applicable to select the most pathogenic SVs?

No, there is no such universal threshold, and we use the scores just to prioritize the variants.

>  Also, do you recommend that even with a low psv in one sample it could be pathogenic if I found the same SV recurrently in at least 30% of the samples? Or any recurrence?

I am not sure this question is specific to SvAnna. In general, common mutations do not lead to rare diseases. So, seeing an SV in many unrelated samples does not support its pathogenicity.

> And, how do I could select the correct (best) transcript? Should be the canonical (1st)?

In rare cases, the "correct" transcript can be tissue specific but most of the time you should pick [MANE](https://www.ncbi.nlm.nih.gov/refseq/MANE/) transcript. Unfortunately, we do not have the MANE attribute in SvAnna, and we did not commit on any specific transcript order in the HTML report, so it should not be relied on.

I hope this helps, please let me know if you have any other questions.
